
/*
2016-03-14  Iwonka utworzenie skryptu tworzącego tabele
*/


CREATE	TABLE walenmar_PORTMONETKI.WALLET
(
ID_WALLET INT(4) NOT NULL,
ID_ACCOUNT INT(4) DEFAULT NULL,
ID_OWNER INT(4) DEFAULT NULL,
TRANS_LIMIT INT(4) DEFAULT 0,
AMMOUNT_LIMIT DECIMAL(6,4) DEFAULT 0.0,
ALLOWED_SHOPS_ID INT(4) DEFAULT NULL,
PRIMARY KEY(ID_WALLET)
)
ENGINE=InnoDB DEFAULT CHARSET=UTF8
--------------------------------------------

CREATE	TABLE walenmar_PORTMONETKI.OWNER
(
ID_OWNER INT(4) NOT NULL,
FIRST_NAME VARCHAR(10) DEFAULT NULL,
LAST_NAME VARCHAR(10) DEFAULT NULL,
ADDRES VARCHAR(10) DEFAULT NULL,
PASSWORD VARCHAR(15) DEFAULT NULL,
SHOP VARCHAR(15) DEFAULT NULL,
PRIMARY KEY(ID_OWNER)
)
ENGINE=InnoDB DEFAULT CHARSET=UTF8
---------------------------------------
CREATE	TABLE walenmar_PORTMONETKI.ACCOUNT_CURRENT
(
ID_ACCOUNT INT(4) NOT NULL,
CURRENCY VARCHAR(3) DEFAULT 'PLN',
BALANCE DECIMAL(6,4) DEFAULT NULL,
ID_OWNER INT(4) DEFAULT NULL,
PRIMARY KEY(ID_ACCOUNT)
)
ENGINE=InnoDB DEFAULT CHARSET=UTF8
---------------------------------------------

CREATE	TABLE walenmar_PORTMONETKI.ACCOUNT_PERIODIC
(
ID_ACCOUNT INT(4) NOT NULL,
CURRENCY VARCHAR(3) DEFAULT 'PLN',
BALANCE DECIMAL(6,4) DEFAULT NULL,
ID_OWNER INT(4) DEFAULT NULL,
PERIOD_DATE DATE DEFAULT NULL,
PERIOD_TIME DATE DEFAULT NULL,
PRIMARY KEY(ID_ACCOUNT,PERIOD_DATE,PERIOD_TIME)
)
ENGINE=InnoDB DEFAULT CHARSET=UTF8
---------------------------------------------

CREATE	TABLE walenmar_PORTMONETKI.TRANSACTION
(
ID_TRANSACTION INT(4) NOT NULL,
SOURCE_ACC INT(4) DEFAULT NULL,
TARGET_ACC INT(4) DEFAULT NULL,
SOURCE_WALLET INT(4) DEFAULT NULL,
TARGET_WALLET INT(4) DEFAULT NULL,
TYPE VARCHAR(3) DEFAULT 'ABC',
PERIOD_DATE DATE DEFAULT NULL,
PERIOD_TIME DATE DEFAULT NULL,
PRIMARY KEY(ID_TRANSACTION)
)
ENGINE=InnoDB DEFAULT CHARSET=UTF8
---------------------------------------------